{% set name = "pyslha" %}
{% set version = "3.2.6" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyslha-{{ version }}.tar.gz
  sha256: 262a604c244db31a07362933001dedc24dd510e803785f9536e8d983ee66e75d
  patches:
    - use-setuptools-over-distutils.patch
    - add-python_requires.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tex2pix >=0.1.5

test:
  imports:
    - pyslha
  commands:
    - pip check

    - slha2isawig --help
    - isawig2slha --help
    - slhaplot --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://www.insectnation.org/projects/pyslha
  summary: Parsing, manipulating, and visualising SUSY Les Houches Accord data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthewfeickert
