schema_version: 1

context:
  name: pyslha
  version: "3.3.0"
  python_min: "3.7"
  commit_ref: "54b4881c500cb1ed2503449d5dad329f5dff20e8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # c.f. https://gitlab.com/hepcedar/pyslha/-/issues/7
  # url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyslha-${{ version }}.tar.gz
  url: https://gitlab.com/hepcedar/pyslha/-/archive/${{ commit_ref }}/pyslha-${{ commit_ref }}.tar.gz
  sha256: dc11986dccffd26f1df3f8b5de1379cd35ee4f7ef617f5c32ae4c1e8e8bd2f1f
  patches:
    - add-requires-python.patch
    - use-argparse-format.patch

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - tex2pix >=0.1.5

tests:
  - python:
      imports:
        - pyslha
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - slha2isawig --help
      - isawig2slha --help
      - slhaplot --help

about:
  summary: Parsing, manipulating, and visualising SUSY Les Houches Accord data
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: http://www.insectnation.org/projects/pyslha
  repository: https://gitlab.com/hepcedar/pyslha/

extra:
  recipe-maintainers:
    - matthewfeickert
